### ISSUE TITLE
files lacking

### ISSUE THREAD

**Issue by MOSHANJESSE** [jch12138/Weather-Station#1]
dear jch,
   Well you know, when i run this project, it reminds me of the lack of files. If you can send files called 'librt_ota_noalgo_0.1.2_stm32l4_keil.lib' and 'libwifi_6181_0.2.5_armcm4_keil.lib', i would be very grateful to you.

**Comment by jch12138** [comment]
thanks for you interested of my project, the lacking file is include in the board sdk, the sdk is here: [SDK](https://github.com/RT-Thread/IoT_Board)

**Comment by jch12138** [comment]
and this project is designed for the specific board which is introduced in the SDK description，if your board is different of it, may be occur some problems.
